<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.hkh</groupId>
        <artifactId>langboot-dependencies</artifactId>
        <version>1.0.0</version>
        <relativePath>../langboot-dependencies</relativePath>
    </parent>

    <artifactId>langboot-user</artifactId>
    <description>用户服务</description>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <profiles>
        <profile>
            <id>dev</id>
            <properties>
                <springboot.profileName>dev</springboot.profileName>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <profile>
            <id>test</id>
            <properties>
                <springboot.profileName>test</springboot.profileName>
            </properties>
        </profile>
        <profile>
            <id>prod</id>
            <properties>
                <springboot.profileName>prod</springboot.profileName>
            </properties>
        </profile>
    </profiles>
    <dependencies>
        <dependency>
            <groupId>com.hkh</groupId>
            <artifactId>langboot-common</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.hkh</groupId>
            <artifactId>langboot-core</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.hkh</groupId>
            <artifactId>langboot-agent</artifactId>
            <version>1.0.0</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
        <resources>
            <!--先排除掉所有的application*.properties-->
            <resource>
                <directory>src/main/resources</directory>
                <excludes>
                    <exclude>application*.properties</exclude>
                </excludes>
            </resource>
            <!--再将对应配置的properties包含在内-->
            <resource>
                <directory>src/main/resources</directory>
                <includes>
                    <include>application.properties</include>
                    <include>application-${springboot.profileName}.properties</include>
                </includes>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>
</project>