<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.hkh</groupId>
    <artifactId>langboot</artifactId>
    <version>1.0.0</version>
    <name>langboot</name>
    <modules>
        <module>langboot-core</module>
        <module>langboot-dependencies</module>
        <module>langboot-admin</module>
        <module>langboot-user</module>
        <module>langboot-common</module>
        <module>langboot-agent</module>
        <module>langboot-domain</module>
    </modules>
    <packaging>pom</packaging>
    <description>SpringBoot + 大预言模型</description>
    <properties>
        <java.version>17</java.version>
    </properties>


</project>
